# Generated by Django 2.2.7 on 2019-11-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='successLogin',
            field=models.BooleanField(default=False),
        ),
    ]
